#include "DataBaseClass.h"

DataBaseClass::DataBaseClass(QObject* parent)
	: QObject(parent)
{
}



DataBaseClass::~DataBaseClass()
{
	if (mainDbConnection.isOpen())
	{
		mainDbConnection.close();
	}

	if (QSqlDatabase::contains("postgres_connection"))
	{
		QSqlDatabase::removeDatabase("postgres_connection");
	}
}



void DataBaseClass::connectionToMainDb(QStringList signalList)
{
	mainDbConnection = QSqlDatabase::addDatabase("QPSQL", "postgres_connection");
	mainDbConnection.setHostName(signalList[0]);
	mainDbConnection.setPort(signalList[1].toInt());  // По умолчанию 5432
	mainDbConnection.setDatabaseName(signalList[2]);
	mainDbConnection.setUserName(signalList[3]);
	mainDbConnection.setPassword(signalList[4]);

	if (!mainDbConnection.open())
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to OPEN database." << "\nError text:\n" << mainDbConnection.lastError().text();
	}
	else
	{
		qDebug() << "OPEN PostgreSQL data base (" << signalList[2] << ')';

		createMainTables();
	}
}



void DataBaseClass::createMainTables()
{
	QSqlQuery query(mainDbConnection);

	if (!query.exec("CREATE TABLE IF NOT EXISTS queue_notice (id_user INT, id_request INT, id_position INT, phone_number VARCHAR(14), mail VARCHAR(40), max_send BOOLEAN, tg_send BOOLEAN, mail_send BOOLEAN, sms_send BOOLEAN, date DATE, time TIME, date_create DATE, time_create TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create queue_notice table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE queue_notice WAS ADD OR SKIP";

	if (!query.exec("CREATE TABLE IF NOT EXISTS history (id_user INT, id_request INT, id_position INT, phone_number VARCHAR(14), mail VARCHAR(40), max_send BOOLEAN, tg_send BOOLEAN, mail_send BOOLEAN, sms_send BOOLEAN, date DATE, time TIME, date_create DATE, time_create TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create history table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE history WAS ADD OR SKIP";

	if (!query.exec("CREATE TABLE IF NOT EXISTS users (id_user INT GENERATED BY DEFAULT AS IDENTITY, mail VARCHAR(25) PRIMARY KEY, password VARCHAR(25), date DATE, time TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create users table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE users WAS ADD OR SKIP";

	if (!query.exec("CREATE TABLE IF NOT EXISTS telegramPhoneTable (chatId VARCHAR(20), phoneNumber VARCHAR(15), date DATE, time TIME, UNIQUE (chatId));"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create telegramPhoneTable table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE telegramPhoneTable WAS ADD OR SKIP";
}



void DataBaseClass::insertInUsers(QString tempMail, QString tempPass)
{
	QSqlQuery query(mainDbConnection);

	query.prepare("INSERT INTO users (mail, password, date, time) VALUES (?, ?, ?, ?) ON CONFLICT (mail) DO NOTHING;");
	query.addBindValue(tempMail);
	query.addBindValue(tempPass);
	query.addBindValue(QDate::currentDate().toString());
	query.addBindValue(QTime::currentTime().toString());

	if (!query.exec())
	{
		qDebug() << "Error in DataBaseClass::insertInUsers() when try to insert value. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "USER was add in users or skip\n";
}



void DataBaseClass::insertInQueueAndHistory(QByteArray arrFromClient)
{
	QJsonDocument jDoc = QJsonDocument::fromJson(arrFromClient.constData());

	if (jDoc.isNull()) {
		qDebug() << "JSON parse error";
		return;
	}

	if (!jDoc.isArray()) {
		qDebug() << "Expected array at root";
		return;
	}

	QJsonArray rootArray = jDoc.array();
	if (rootArray.isEmpty()) return;

	qDebug() << "Processing" << rootArray.size() << "task objects";

	// Проходим по всем объектам в корневом массиве (task1, task2, task3...)
	for (int taskIndex = 0; taskIndex < rootArray.size(); ++taskIndex) {
		QJsonValue rootValue = rootArray[taskIndex];

		if (!rootValue.isObject()) {
			qDebug() << "Skipping non-object at index" << taskIndex;
			continue;
		}

		QJsonObject taskObj = rootValue.toObject();

		QString userId = taskObj["userId"].toString();
		QString numberTask = taskObj["numberTask"].toString();

		QJsonArray messegeArray = taskObj["messegeArray"].toArray();

		qDebug() << "Task" << taskIndex + 1 << "- userId:" << userId
			<< "numberTask:" << numberTask
			<< "messages:" << messegeArray.size();

		// Для каждого сообщения в массиве сообщений текущей задачи
		for (int msgIndex = 0; msgIndex < messegeArray.size(); ++msgIndex) {
			QJsonValue msgValue = messegeArray[msgIndex];

			if (!msgValue.isObject()) {
				qDebug() << "Skipping non-object message at index" << msgIndex;
				continue;
			}

			QJsonObject msgObj = msgValue.toObject();

			// Формируем список значений для вставки
			QStringList values;
			values << userId;                                   // id_user
			values << numberTask;                               // id_request
			values << msgObj["numberMessege"].toString();      // id_position
			values << msgObj["phoneNumber"].toString();        // phone_number
			values << msgObj["mail"].toString();               // mail
			values << (msgObj["sendMax"].toInt() == 2 ? "true" : "false");      // max_send
			values << (msgObj["sendTelegram"].toInt() == 2 ? "true" : "false"); // tg_send
			values << (msgObj["sendMail"].toInt() == 2 ? "true" : "false");     // mail_send
			values << (msgObj["sendSms"].toInt() == 2 ? "true" : "false");      // sms_send
			values << msgObj["date"].toString();               // date
			values << msgObj["time"].toString();               // time

			QString dateCreate = QDate::currentDate().toString("yyyy-MM-dd");
			QString timeCreate = QTime::currentTime().toString();

			qDebug() << "  Message" << msgIndex + 1 << ":" << values;

			// Вставка в таблицы (queue_notice и history)
			for (int countTable = 1; countTable <= 2; countTable++) 
			{
				QSqlQuery query(mainDbConnection);

				QString tableName = (countTable == 1) ? "queue_notice" : "history";

				QString queryStr = QString("INSERT INTO %1 (id_user, id_request, id_position, phone_number, mail, max_send, tg_send, mail_send, sms_send, date, time, date_create, time_create) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);")
					.arg(tableName);

				query.prepare(queryStr);

				// Добавляем все 13 значений
				for (const QString& value : values) {
					query.addBindValue(value);
				}
				query.addBindValue(dateCreate);
				query.addBindValue(timeCreate);

				if (!query.exec()) 
				{
					qDebug() << "ERROR inserting into" << tableName;
					qDebug() << "  Values:" << values;
					qDebug() << "  DateCreate:" << dateCreate << "TimeCreate:" << timeCreate;
					qDebug() << "  Error:" << query.lastError().text();
				}
				else 
				{
					qDebug() << "  SUCCESS inserted into" << tableName;
				}
			}
		}
	}

	qDebug() << "Finished processing all tasks";
}



void DataBaseClass::getQueueValue()
{
	QList<QStringList>tempQListWIthStringList;
	QString queryString = QString("SELECT * FROM queue_notice ORDER BY date, time");

	if (mainDbConnection.isOpen())
	{
	}
	else
	{
		if (!mainDbConnection.open())
		{
			qDebug() << "Error in DataBaseClass::getQueueValue() when check database is OPEN." << "\nError text:\n" << mainDbConnection.lastError().text();
			return;
		}
		else
		{
			qDebug() << "Reconnect to PostgreSQL data base (" << mainDbConnection.databaseName() << ')';
		}
	}

	QSqlQuery query(mainDbConnection);

	if (!query.exec(queryString) || !query.next())
	{
		if (query.lastError().isValid())
		{
			qDebug() << "Error in DataBaseClass::getQueueValue() when try to get values from queue_notice. Error:\n" << query.lastError().text() << "Query: \n" << query.lastQuery();
		}
		else
			qDebug() << QDate::currentDate().toString("yyyy-MM-dd") << " " << QTime::currentTime() << " NOT GET from queue_notice";
	}
	else
	{
		QStringList tempStringList;
		QString chatIdForTgInSignal = "";

		for (int counter = 0; counter < 11; counter++)
		{
			tempStringList << query.value(counter).toString();
		}

		if (tempStringList[6] == "true")
		{
			QString temp = tempStringList[3].sliced(2);

			if (!query.exec(QString("SELECT chatId FROM telegramPhoneTable WHERE phoneNumber LIKE '%%1'").arg(temp)) || !query.next())
			{
				if (query.lastError().isValid())
				{
					qDebug() << "Error in DataBaseClass::getQueueValue() when try to get chatId from queue_notice. Error:\n" << query.lastError().text() << "Query: \n" << query.lastQuery();
				}
				//else
				//	qDebug() << QDate::currentDate().toString("yyyy-MM-dd") << " " << QTime::currentTime() << " NOT GET ChatId from queue_notice";
			}
			else
				chatIdForTgInSignal = query.value(0).toString();
		}

		emit sendStringListFromQueue(tempStringList, chatIdForTgInSignal);
	}
}



void DataBaseClass::deleteFromDb(QString Id, QString request, QString pos)
{
	QSqlQuery query(mainDbConnection);
	QString queryString = QString("DELETE FROM queue_notice WHERE");

	query.prepare("DELETE FROM queue_notice WHERE id_user = ? AND id_request = ? AND id_position = ?");
	query.addBindValue(Id);
	query.addBindValue(request);
	query.addBindValue(pos);

	if (!query.exec())
	{
		if (query.lastError().isValid())
		{
			qDebug() << "Error in DataBaseClass::deleteFromDb() when try delete value in queue_notice. Error:\n" << query.lastError().text() << "Query: \n" << query.lastQuery();
		}
		else
			qDebug() << "NOT DELETE in queue_notice";
	}
	else
	{
		qDebug() << "VALUE WAS DELETE in queue_notice";
	}
}



void DataBaseClass::insertInTelegramPhoneTable(QString chat, QString phone)
{
	QSqlQuery query(mainDbConnection);

	query.prepare("INSERT INTO telegramPhoneTable (chatId, phoneNumber, date, time) VALUES (?, ?, ?, ?) ON CONFLICT (chatId) DO UPDATE SET phoneNumber = excluded.phoneNumber, date = excluded.date, time = excluded.time;");
	query.addBindValue(chat);
	query.addBindValue(phone);
	query.addBindValue(QDate::currentDate().toString("yyyy-MM-dd"));
	query.addBindValue(QTime::currentTime().toString());

	if (!query.exec())
	{
		qDebug() << "Error in DataBaseClass::insertInTelegramPhoneTable() when try to telegramPhoneTable value. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "ChatID / PHONE was add in telegramPhoneTable or update\n";
}
