#include "DataBaseClass.h"

DataBaseClass::DataBaseClass(QObject* parent)
	: QObject(parent)
{
}



DataBaseClass::~DataBaseClass()
{
	if (mainDbConnection.isOpen())
	{
		mainDbConnection.close();
	}

	if (QSqlDatabase::contains("postgres_connection"))
	{
		QSqlDatabase::removeDatabase("postgres_connection");
	}
}



void DataBaseClass::connectionToMainDb(QStringList signalList)
{
	mainDbConnection = QSqlDatabase::addDatabase("QPSQL", "postgres_connection");
	mainDbConnection.setHostName(signalList[0]);
	mainDbConnection.setPort(signalList[1].toInt());  // ѕо умолчанию 5432
	mainDbConnection.setDatabaseName(signalList[2]);
	mainDbConnection.setUserName(signalList[3]);
	mainDbConnection.setPassword(signalList[4]);

	if (!mainDbConnection.open())
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to OPEN database." << "\nError text:\n" << mainDbConnection.lastError().text();
	}
	else
	{
		qDebug() << "OPEN " << signalList[2];

		createMainTables();
	}
}



void DataBaseClass::createMainTables()
{
	QSqlQuery query(mainDbConnection);

	if (!query.exec("CREATE TABLE IF NOT EXISTS queue_notice (id_user INT, id_request INT, id_position INT, phone_number VARCHAR(14), mail VARCHAR(40), max_send BOOLEAN, tg_send BOOLEAN, mail_send BOOLEAN, sms_send BOOLEAN, date DATE, time TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create queue_notice table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE queue_notice WAS ADD OR SKIP";

	if (!query.exec("CREATE TABLE IF NOT EXISTS history (id_user INT, id_request INT, id_position INT, phone_number VARCHAR(14), mail VARCHAR(40), max_send BOOLEAN, tg_send BOOLEAN, mail_send BOOLEAN, sms_send BOOLEAN, date DATE, time TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create history table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE history WAS ADD OR SKIP";

	if (!query.exec("CREATE TABLE IF NOT EXISTS users (id_user INT GENERATED BY DEFAULT AS IDENTITY, mail VARCHAR(25) PRIMARY KEY, password VARCHAR(25), date DATE, time TIME);"))
	{
		qDebug() << "Error in DataBaseClass::connectionToMainDb() when try to create users table. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "TABLE users WAS ADD OR SKIP";
}



void DataBaseClass::insertInUsers(QString tempMail, QString tempPass)
{
	QSqlQuery query(mainDbConnection);

	query.prepare("INSERT INTO users (mail, password, date, time) VALUES (?, ?, ?, ?) ON CONFLICT (mail) DO NOTHING;");
	query.addBindValue(tempMail);
	query.addBindValue(tempPass);
	query.addBindValue(QDate::currentDate().toString());
	query.addBindValue(QTime::currentTime().toString());

	if (!query.exec())
	{
		qDebug() << "Error in DataBaseClass::insertInUsers() when try to insert value. Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
	}
	else
		qDebug() << "VALUE was add in users";
}



void DataBaseClass::insertInQueueAndHistory(QStringList tempList)
{
	QSqlQuery query(mainDbConnection);
	QString date = QDate::currentDate().toString();
	QString time = QTime::currentTime().toString();

	for (int countTable = 1; countTable <= 2; countTable++)
	{
		// ¬ Postgre подготовленный запрос на вставку в таблицу почему то иначе интрепретируетс€ и будет гарантированна€ ошибка. ƒелаем дл€ таблицы втсавку через .arg() если это требуетс€.
		query.prepare(QString("INSERT INTO %1 (id_user, id_request, id_position, phone_number, mail, max_send, tg_send, mail_send, sms_send, date, time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);")
			.arg(countTable == 1 ? "queue_notice" : "history"));

		query.addBindValue(tempList[0]);
		query.addBindValue(tempList[1]);
		query.addBindValue(tempList[2]);
		query.addBindValue(tempList[3]);
		query.addBindValue(tempList[4]);
		query.addBindValue(tempList[5]);
		query.addBindValue(tempList[6]);
		query.addBindValue(tempList[7]);
		query.addBindValue(tempList[8]);
		query.addBindValue(date);
		query.addBindValue(time);

		if (!query.exec())
		{
			qDebug() << "Error in DataBaseClass::insertInQueueAndHistory() when try to insert value in " << (countTable == 1 ? "queue_notice" : "history") << ". Query:\n" << query.lastQuery() << "\nError text:\n" << query.lastError().text();
		}
		else
			qDebug() << "VALUE was add in " << (countTable == 1 ? "queue_notice" : "history");
	}
}



void DataBaseClass::getQueueValue()
{
	QList<QStringList>tempQListWIthStringList;
	QSqlQuery query(mainDbConnection);
	QString queryString = QString("SELECT * FROM queue_notice ORDER BY date, time");

	if (!query.exec(queryString) || !query.next())
	{

		if (query.lastError().isValid())
		{
			qDebug() << "Error in DataBaseClass::getQueueValue() when try to get values from queue_notice. Error:\n" << query.lastError().text() << "Query: \n" << query.lastQuery();
		}
		else
			qDebug() << "NOT GET from queue_notice";
	}
	else
	{
		QStringList tempStringList;

		for (int counter = 0; counter < 11; counter++)
		{
			tempStringList << query.value(counter).toString();
		}

		emit sendSTringListFromQueue(tempStringList);
	}
}